# Site settings
title: Edmund Wright
email: edmundewright@gmail.com
url: xneophyte.github.io
description: "Edmund Wright is technologist and maker with a passion for curiosity and learning. A versatile problem solver who blends a background in electronics and software development with industry experience in product R&D and industrial automation."
keywords: "Edmund Wright, Edmund, Wright, Software, Architect, Engineer"
skills: "Software Architecture - New Product R&D - Industrial Automation"
meta_author: Wright Edmund

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF header and about color
  primary-rgb: "24,288,156" #"128,179,255" portfolio link color
  secondary: 2c3e50 #FD6E8A header and footer color
  secondary-dark: 233140 #A2122F content credits color

# Footer settings
footer:
  copyright: Edmund E. Wright II
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, facebook, bitbucket, stack-overflow, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/edmundewright
  - title: github
    url: https://github.com/xNeophyte
  - title: twitter
    url: https://twitter.com/edisawesome

# Postal address (add as many lines as necessary)
address:
  - line: Chicago, IL. USA

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
